export type Language = 'FR' | 'EN' | 'ES' | 'PT';

export const translations = {
  FR: {
    nav: { agency: "L'Agence", results: "Résultats", muses: "Modèles", apply: "Candidature 🚀" },
    hero: { tag: "MANAGEMENT DE CRÉATRICES EXCLUSIF", title1: "Nous gérons", title2: "des carrières.", desc: "L'agence d'élite réservée aux créatrices qui refusent la médiocrité. Des stratégies agressives, une direction artistique luxueuse et une rentabilité maximale respectant votre anonymat.", btn1: "Postuler Maintenant", btn2: "Voir nos résultats", partners: "Partenaires :", today: "Aujourd'hui", new_fan: "Nouveau Fan", vip_tier: "Tier VIP" },
    footer: { rights: "© 2026 OnlyOne Management. Tous droits réservés." },
    painpoints: { tag: "La vérité du marché", title1: "Faire cavalier seul, c'est", title2: "plafonner", desc: "Le marché évolue. 95% des créatrices s'épuisent seules face à une charge de travail invisible. Pendant ce temps, le Top 1% s'appuie sur une équipe d'experts.", alone: { title: "Sans Accompagnement", items: [{ title: "Temps Perdu en Messages", desc: "Échanger des heures durant avec des profils qui ne concrétisent jamais leurs achats. C'est une perte d'énergie massive." }, { title: "Manque de Visibilité", desc: "Publier quotidiennement dans l'indifférence. Sans réseau professionnel, votre audience reste limitée." }, { title: "Revenus Plafonnés", desc: "Rester bloquée au même palier financier mois après mois sans stratégie." }, { title: "Démotivation & Isolement", desc: "9 créatrices sur 10 finissent par abandonner par manque d'accompagnement réel." }, { title: "Agences Non-Professionnelles", desc: "Confier votre image à des structures sans croissance concrète." }] }, agency: { title: "Avec L'Agence OnlyOne", items: [{ title: "Gestion des Ventes 24h/24", desc: "Nous filtrons, gérons et optimisons vos ventes de contenus en continu." }, { title: "Promotion & Acquisition", desc: "Grâce à nos réseaux, nous attirons quotidiennement de nouveaux abonnés qualifiés." }, { title: "Direction Artistique", desc: "Nous vous guidons sur les formats qui génèrent le plus de profit." }, { title: "Accompagnement 7j/7", desc: "Un manager dédié vous accompagne quotidiennement. Vous n'êtes plus seule." }, { title: "Anonymat & Protection", desc: "Protection de votre identité et effacement des fuites." }], cta: "Passez au niveau supérieur", btn: "Postuler à l'agence" } },
    services: { tag: "Notre Expertise", title1: "Accélérez votre", title2: "Croissance", desc: "Nous développons de réelles marques personnelles et optimisons l'engagement à 100%.", items: [{ title: "Dominez l'algorithme", desc: "Des stratégies d'acquisition agressives. On s'occupe du trafic, vous créez librement." }, { title: "Personal Branding", desc: "Forgée pour être luxueuse et captivante à long terme." }, { title: "Gestion et Vente H24", desc: "Notre équipe maximise vos revenus de jour comme de nuit, passivement." }, { title: "Protection Absolue", desc: "Sûreté juridique et tracking DMCA retirant toutes sources illégales." }] },
    simulator: { tag: "CALCULATEUR ROI", title1: "La psychologie de", title2: "l'audience", desc: "L'implication personnelle décuple les résultats de l'audience.", label: "Votre Audience Actuelle (Followers IG/TikTok)", subs: "abonnés", monthly: "Revenus Mensuels Estimés", to: "à", disclaimer: "Rien n'est garanti.", disclaimer_text: "Cette estimation peut énormément varier suivant les profils. Cela dépend surtout de votre capacité à produire.", btn: "Débloquer mon potentiel" },
    results: { tag: "RÉSULTATS PROUVÉS", title1: "Des performances", title2: "concrètes", before: "Avant", start: "Début", after3m: "Après 3 Mois", months: ["Janv", "Fév", "Mars"], growth_title: "Croissance Exponentielle", growth_desc: "L'audience se transforme mécaniquement en MRR (revenu mensuel récurrent).", stability_title: "Stabilité des Revenus", stability_desc: "Une rétention haut de gamme (upsells, chatteurs qualifiés) pour lisser vos revenus chaque mois à la hausse." },
    models: { tag: "Notre roster exclusif", title1: "Nos Top", title2: "Modèles" },
    reviews: { m1: "Bordel j'y crois pas j'ai fait +4k en 3 jours !! 😍", m2: "Et c'est que le début. Les campagnes US viennent à peine de démarrer. 🚀", m3: "Omg d'accord je fais ça direct dans l'aprem !! ✨", online: "En ligne", tag: "RÉSEAU SILENCIEUX", title1: "Des succès", title2: "Confidentiels", desc: "Notre messagerie privée est le seul endroit où nos talents réalisent à quel point leur vie a changé.", accompanied: "Modèles accompagnées vers le Top 1%" },
    faq: { tag: "TRANSPARENCE TOTALE", title1: "Vos questions", title2: "fréquentes", items: [{ q: "Puis-je rester anonyme et bloquer mes proches ?", a: "Absolument. Dès le premier jour, nous mettons en place des blocages stricts." }, { q: "Qui répond aux messages sur mon compte ?", a: "Notre équipe de confiance spécifiquement entraînée, vendant en toute sécurité." }, { q: "Je n'ai jamais fait ça, allez-vous m'aider à démarrer ?", a: "Oui, à 100%. L'agence s'occupe de quasiment tout." }, { q: "En combien de temps puis-je gagner mes premiers revenus ?", a: "Dès que votre compte est configuré, l'argent peut rentrer massivement dès le premier mois." }] },
    onboarding: { tag: "NOTRE PROCESSUS", title1: "L'Onboarding", title2: "Exclusif", desc: "Une méthodologie chirurgicale sur 30 jours pour vous transformer en machine à cash.", items: [{ title: "Audit & Stratégie", desc: "Analyse complète de vos réseaux et définition de cap." }, { title: "Setup & Sécurité", desc: "Configuration de vos plateformes et blocage géographique." }, { title: "Lancement & Trafic", desc: "Déploiement agressif de nos tunnels d'acquisition VIP." }, { title: "Scaling H24", desc: "Ventes additionnelles maximisées 24h/24 pendant la nuit." }] },
    form: { title: "Soumettre votre candidature", desc: "Nous n'acceptons que 2 nouveaux talents par mois pour garantir la qualité supérieure.", name: "Prénom / Pseudo", email: "Adresse Email", socials: "Vos Réseaux Sociaux", has_platform: "Avez-vous déjà une plateforme privée (MYM, OF, Fanvue...) ?", has_platform_no: "Non, je souhaite démarrer et me faire accompagner", has_platform_yes: "Oui, je suis déjà active sur une plateforme", has_platform_past: "J'ai essayé par le passé sans succès", which_platform: "Laquelle ?", platform_link: "Lien de la plateforme", motivations: "Vos Motivations & Objectifs", motivations_ph: "Parlez-nous de vous, vos limites, vos objectifs financiers.", submit: "Envoyer ma candidature confidentielle", submitting: "Transmission Sécurisée...", secure_note: "⚠️ Transmission chiffrée & Strictement Confidentielle", success_title: "Candidature Envoyée", success_desc: "Nous avons bien reçu votre profil de manière hautement sécurisée. Si votre dossier correspond à nos critères d'élite, notre équipe prendra contact avec vous dans les 48 heures.", success_btn: "Soumettre une autre candidature" }
  },
  EN: {
    nav: { agency: "The Agency", results: "Results", muses: "Models", apply: "Apply Now 🚀" },
    hero: { tag: "EXCLUSIVE CREATOR MANAGEMENT", title1: "We manage", title2: "careers.", desc: "An elite agency reserved for creators who refuse mediocrity. Aggressive strategies, luxurious art direction, and maximum profitability while respecting your anonymity.", btn1: "Apply Now", btn2: "View our results", partners: "Partners:", today: "Today", new_fan: "New Fan", vip_tier: "VIP Tier" },
    footer: { rights: "© 2026 OnlyOne Management. All rights reserved." },
    painpoints: { tag: "The market reality", title1: "Going solo means", title2: "hitting a ceiling", desc: "The market is evolving. 95% of creators burn out facing an invisible workload alone. Meanwhile, the Top 1% relies on an expert team to dominate the rankings.", alone: { title: "Without Support", items: [{ title: "Time Wasted on Messages", desc: "Exchanging for hours with profiles who never concretize their purchases. It's a massive loss of energy." }, { title: "Lack of Visibility", desc: "Posting daily in indifference. Without a professional network, your audience remains limited." }, { title: "Capped Income", desc: "Staying stuck at the same financial level month after month without an advanced sales strategy." }, { title: "Demotivation & Isolation", desc: "9 out of 10 creators end up quitting due to a lack of real guidance." }, { title: "Unprofessional Agencies", desc: "Entrusting your image to structures that provide no concrete work for your growth." }] }, agency: { title: "With OnlyOne Agency", items: [{ title: "24/7 Sales Management", desc: "We filter solicitations and continuously optimize your content sales." }, { title: "Promotion & Acquisition", desc: "Through our networks, we daily attract new qualified subscribers to your profile." }, { title: "Art Direction", desc: "We guide you on the formats and themes that generate the most profit." }, { title: "24/7 Guidance", desc: "A dedicated manager accompanies you daily to steer your growth. You are no longer alone." }, { title: "Anonymity & Protection", desc: "Protection of your identity and precise geo-blocking. We remove content leaks." }], cta: "Go to the next level", btn: "Apply to the agency" } },
    services: { tag: "Our Expertise", title1: "Accelerate your", title2: "Growth", desc: "Beyond classic administration, we develop genuine personal brands and optimize engagement to 100%.", items: [{ title: "Dominate the algorithm", desc: "Aggressive acquisition strategies to grow your platforms in record time. We handle the traffic." }, { title: "Personal Branding", desc: "We forge a luxurious and irresistible image that captivates your audience." }, { title: "24/7 Management & Sales", desc: "Our team of specialists takes over. They maximize your income day and night, for passive growth." }, { title: "Absolute Protection", desc: "Legal security and daily DMCA tracking. Your content is protected." }] },
    simulator: { tag: "ROI CALCULATOR", title1: "The psychology of", title2: "audience", desc: "Follower count isn't everything. Audience niche and personal involvement multiply results.", label: "Your Current Audience (IG/TikTok Followers)", subs: "followers", monthly: "Estimated Monthly Revenue with OnlyOne", to: "to", disclaimer: "Nothing is guaranteed.", disclaimer_text: "This estimation can vary enormously depending on profiles. Results mainly depend on your ability to produce real content.", btn: "Unlock my potential" },
    results: { tag: "PROVEN RESULTS", title1: "Concrete", title2: "performances", before: "Before", start: "Start", after3m: "After 3 Months", months: ["Jan", "Feb", "Mar"], growth_title: "Exponential Growth", growth_desc: "By deploying our acquisition funnels, the audience mechanically transforms into MRR (monthly recurring revenue).", stability_title: "Revenue Stability", stability_desc: "We use high-end retention strategies (upsells, qualified chatters) to smooth your revenue upwards every month." },
    models: { tag: "Our exclusive roster", title1: "Our Top", title2: "Models" },
    reviews: { m1: "Damn I can't believe it I made +4k in 3 days !! 😍", m2: "And it's just the beginning. The US campaigns have barely started. 🚀", m3: "Omg okay I'll do that right this afternoon !! ✨", online: "Online", tag: "SILENT NETWORK", title1: "Confidential", title2: "successes", desc: "We operate in the shadows. Our private messages are the only place our talents realize how much their lives have changed.", accompanied: "Models accompanied to the Top 1%" },
    faq: { tag: "TOTAL TRANSPARENCY", title1: "Your frequent", title2: "questions", items: [{ q: "Can I remain anonymous and block my relatives?", a: "Absolutely. Your privacy is our top priority. From day one, we implement strict blocking by city or country." }, { q: "Who replies to messages on my account?", a: "Our trusted team, specifically trained for you. They take care of selling your private photos safely." }, { q: "I've never done this, will you help me start?", a: "Yes, 100%. The agency takes care of almost everything." }, { q: "How long until I earn my first income?", a: "As soon as your account is set up, you can see money coming in massively from the first month." }] },
    onboarding: { tag: "OUR PROCESS", title1: "Exclusive", title2: "Onboarding", desc: "No luck involved. A surgical 30-day methodology to turn you into a cash-generating machine.", items: [{ title: "Audit & Strategy", desc: "Complete analysis of your social networks and creation of a personalized roadmap." }, { title: "Setup & Security", desc: "Configuration of your platforms and geo-blocking if needed." }, { title: "Launch & Traffic", desc: "Deployment of our aggressive acquisition funnels to send qualified traffic." }, { title: "24/7 Scaling", desc: "Taken over by our chat team. Additional sales maximized 24/7." }] },
    form: { title: "Submit your application", desc: "We only accept 2 new talents per month to guarantee exceptional guidance.", name: "First Name / Nickname", email: "Email Address", socials: "Your Social Networks", has_platform: "Do you already have a private platform (MYM, OF, Fanvue...)?", has_platform_no: "No, I want to start and be guided", has_platform_yes: "Yes, I am already active on a platform", has_platform_past: "I've tried in the past without success", which_platform: "Which one?", platform_link: "Platform Link or Nickname", motivations: "Your Motivations & Goals", motivations_ph: "Tell us about yourself, your limits, your financial goals.", submit: "Send my confidential application", submitting: "Secure Transmission...", secure_note: "⚠️ Encrypted & Strictly Confidential Transmission", success_title: "Application Sent", success_desc: "We have safely received your profile. If your application meets our elite criteria, our team will contact you within 48 hours.", success_btn: "Submit another application" }
  },
  ES: {
    nav: { agency: "La Agencia", results: "Resultados", muses: "Modelos", apply: "Postularse 🚀" },
    hero: { tag: "MANAGEMENT EXCLUSIVO DE CREADORAS", title1: "Gestionamos", title2: "carreras.", desc: "La agencia de élite reservada para creadoras que rechazan la mediocridad. Estrategias agresivas, dirección artística de lujo y rentabilidad máxima respetando tu anonimato.", btn1: "Postularse Ahora", btn2: "Ver resultados", partners: "Socios:", today: "Hoy", new_fan: "Nuevo Fan", vip_tier: "Nivel VIP" },
    footer: { rights: "© 2026 OnlyOne Management. Todos los derechos reservados." },
    painpoints: { tag: "La realidad del mercado", title1: "Ir por tu cuenta es", title2: "tocar techo", desc: "El mercado evoluciona. El 95% de las creadoras se agotan solas frente a una carga de trabajo invisible. Mientras tanto, el Top 1% se apoya en un equipo experto.", alone: { title: "Sin Acompañamiento", items: [{ title: "Tiempo Perdido en Mensajes", desc: "Intercambiar mensajes horas con perfiles que nunca compran es una pérdida de energía masiva." }, { title: "Falta de Visibilidad", desc: "Publicar a diario en la indiferencia. Sin una red profesional, tu audiencia queda limitada." }, { title: "Ingresos Estancados", desc: "Quedar atrapada en el mismo nivel mes tras mes sin estrategia avanzada de ventas." }, { title: "Desmotivación y Aislamiento", desc: "9 de cada 10 creadoras terminan abandonando por falta de acompañamiento real." }, { title: "Agencias No Profesionales", desc: "Confiar tu imagen a estructuras sin crecimiento concreto comprobado." }] }, agency: { title: "Con OnlyOne Agency", items: [{ title: "Gestión de Ventas 24/7", desc: "Filtramos solicitudes y optimizamos tus ventas de contenidos continuamente." }, { title: "Promoción y Adquisición", desc: "Gracias a nuestras redes, atraemos a diario nuevos suscriptores calificados." }, { title: "Dirección Artística", desc: "Te guiamos sobre los formatos y temáticas que generan más beneficios." }, { title: "Acompañamiento 24/7", desc: "Un mánager dedicado te acompaña diariamente. Ya no trabajas sola." }, { title: "Anonimato y Protección", desc: "Protección de identidad y bloqueo geográfico. Rastreamos fugas." }], cta: "Pasa al siguiente nivel", btn: "Ir a la agencia" } },
    services: { tag: "Nuestra Experiencia", title1: "Acelera tu", title2: "Crecimiento", desc: "Desarrollamos marcas personales genuinas y optimizamos la interacción al 100%.", items: [{ title: "Domina el algoritmo", desc: "Estrategias de adquisición agresivas. Nosotros nos ocupamos del tráfico." }, { title: "Personal Branding", desc: "Forjamos una imagen irresistible que cautiva a tu público." }, { title: "Gestión Chat 24/7", desc: "Expertos toman los mandos hablando y maximizando los ingresos por ti." }, { title: "Protección Completa", desc: "Auditoría legal DMCA eliminando toda huella maliciosa ajena." }] },
    simulator: { tag: "CALCULADORA DE ROI", title1: "La psicología de", title2: "la audiencia", desc: "La cantidad de seguidores no lo es todo. El nicho y la implicación personal multiplican tus resultados en las ganancias.", label: "Tu Audiencia Actual (Seguidores IG/TikTok)", subs: "seguidores", monthly: "Ingresos Mensuales Estimados con OnlyOne", to: "a", disclaimer: "Nada está garantizado.", disclaimer_text: "Esta estimación puede variar dependiendo de los perfiles individuales. Los resultados dependen de tu capacidad para producir de forma constante.", btn: "Desbloquear mi potencial" },
    results: { tag: "RESULTADOS COMPROBADOS", title1: "Rendimientos", title2: "concretos", before: "Antes", start: "Inicio", after3m: "Tras 3 Meses", months: ["Ene", "Feb", "Mar"], growth_title: "Crecimiento Exponencial", growth_desc: "Al implementar los embudos, la audiencia se transforma en ingresos recurrentes (MRR).", stability_title: "Estabilidad de Ingresos", stability_desc: "Usamos diferentes estrategias de retención premium con ventas ascendentes para estabilizar y aumentar las ganancias." },
    models: { tag: "Nuestro portfolio VIP", title1: "Nuestras Top", title2: "Modelos" },
    reviews: { m1: "¡No me lo creo he hecho +4k en 3 días! 😍", m2: "Y es solo el principio. Las campañas en US acaban de empezar. 🚀", m3: "¡OMG perfecto, me pongo a ello ahora mismo! ✨", online: "En línea", tag: "RED SECRETA", title1: "Éxitos", title2: "Confidentes", desc: "Operamos en las sombras para llevar a nuestras modelos a la luz del éxito pleno. Los mensajes privados con la agencia son el único lugar donde observan su éxito masivo.", accompanied: "Modelos apoyadas directamente hacia el codiciado 1%" },
    faq: { tag: "TRANSPARENCIA TOTAL", title1: "Preguntas", title2: "frecuentes", items: [{ q: "¿Puedo permanecer anónima y bloquear conocidos?", a: "Absolutamente sí. Tu privacidad es siempre nuestra prioridad número uno. Ponemos bloqueos geográficos estrictos." }, { q: "¿Quién responde a los mensajes en mi cuenta?", a: "Nuestro calificado y persuasivo equipo. Conversan emulando en toda perfección tus características." }, { q: "Nunca he hecho esto ¿Me guiarán desde el comienzo?", a: "Sí, al cien por ciento en cada paso. Nuestra agencia se hace cargo de casi todo." }, { q: "¿En cuánto tiempo podré ver beneficios notables?", a: "Los plazos suelen mostrar picos rápidos usualmente durante su primer mes con OnlyOne." }] },
    onboarding: { tag: "NUESTRO PROCESO", title1: "Onboarding", title2: "Premium", desc: "Una metodología quirúrgica de 30 días para convertirte en una máquina de generar ingresos.", items: [{ title: "Auditoría VIP", desc: "Nos cercioramos de aplicar planes estéticos puros exactos al mercado." }, { title: "Setup Tecnológico", desc: "Blindaje absoluto aplicando DMCA sin cese borrando toda fuga." }, { title: "Tráfico Masivo", desc: "Aprovechamos campañas internacionales enviando público rico a tu cuenta VIP." }, { title: "Scaling 24/7", desc: "Tus ventas adicionales se maximizan 24/7 con nuestro chat." }] },
    form: { title: "Ingresar Candidatura", desc: "Aceptamos solamente a 2 creadoras nuevas por mes.", name: "Tu Nombre o Alias", email: "Cuenta de Correo Electrónico", socials: "Enlaces a redes sociales", has_platform: "¿Ya cuentas con plataforma pagada activamente?", has_platform_no: "No, busco iniciar mi andadura", has_platform_yes: "Sí, cuento con mis ingresos", has_platform_past: "Se estancó al intentarlo antes", which_platform: "¿Cuál es?", platform_link: "Usuario Oficial de la cuenta", motivations: "Tus aspiraciones al asociarnos", motivations_ph: "Menciona lujos soñados o tu objetivo financiero de cada mes...", submit: "Enviar Candidatura Confidencialmente", submitting: "Cargando el Sistema Seguro...", secure_note: "Tranquilidad garantizada. Cifrado en tránsito totalmente seguro inviolado.", success_title: "Expediente Recibido Correctamente", success_desc: "Toda tu información está siendo analizada. Responderemos según tu perfil en 48 horas.", success_btn: "Subir un Formulario Extra" }
  },
  PT: {
    nav: { agency: "A Agência", results: "Resultados", muses: "Modelos", apply: "Inscrever-se 🚀" },
    hero: { tag: "GESTÃO DE CRIADORAS EXCLUSIVA", title1: "Nós gerimos", title2: "carreiras.", desc: "A agência de elite reservada para criadoras que recusam a mediocridade. Estratégias agressivas, direção artística luxuosa e rentabilidade máxima, respeitando o seu anonimato.", btn1: "Candidatar-me Agora", btn2: "Ver resultados", partners: "Parceiros:", today: "Hoje", new_fan: "Novo Fã", vip_tier: "Tier VIP" },
    footer: { rights: "© 2026 OnlyOne Management. Todos os direitos reservados." },
    painpoints: { tag: "A realidade do mercado", title1: "Trabalhar sozinha é", title2: "bater no teto", desc: "O mercado evolui. 95% das criadoras esgotam-se sozinhas perante uma carga de trabalho invisível. Entretanto, o Top 1% apoia-se numa equipa de especialistas.", alone: { title: "Sem Apoio", items: [{ title: "Tempo Perdido em Mensagens", desc: "Passar horas conversando com perfis que nunca finalizam a compra. É um desperdício enorme de energia." }, { title: "Falta de Visibilidade", desc: "Publicar diariamente na indiferença. Sem uma rede profissional, a sua audiência permanece estagnada." }, { title: "Rendimentos Estagnados", desc: "Ficar presa no mesmo valor financeiro mês após mês sem estratégia de venda." }, { title: "Desmotivação & Isolamento", desc: "9 em cada 10 criadoras desistem por falta de acompanhamento adequado." }, { title: "Agências Amadoras", desc: "Confiar a sua imagem a parceiros que não cumprem o trabalho de promoção." }] }, agency: { title: "Com a OnlyOne", items: [{ title: "Gestão de Vendas 24/7", desc: "Filtramos os pedidos e gerimos ativamente a venda do seu conteúdo de forma otimizada." }, { title: "Promoção & Aquisição", desc: "Graças à nossa rede, atraímos diariamente novos fãs ao seu perfil VIP." }, { title: "Direção Artística", desc: "Aconselhamos os formatos que geram o máximo lucro sem perda de tempo." }, { title: "Apoio Contínuo", desc: "Um gestor acompanha diretamente o seu percurso. Nunca caminhará sozinha." }, { title: "Anonimato & Proteção", desc: "Proteção geográfica exata e rastreio para remover fugas de publicações na web." }], cta: "Avançar de nível", btn: "Candidatar-me" } },
    services: { tag: "A Nossa Experiência", title1: "Acelere o seu", title2: "Crescimento", desc: "Desenvolvemos marcas pessoais de luxo autênticas de modo a otimizar a interação em 100%.", items: [{ title: "Domine o algoritmo", desc: "Processo de atração agressivo a alta velocidade. Você apenas produz." }, { title: "Branding Pessoal", desc: "Forjamos uma imagem irresistível, atraindo atenção do seu mercado em peso." }, { title: "Gestão e Chat 24/7", desc: "Uma conversão incessante trabalhando no seu chat, multiplicando os ganhos por comissões diárias." }, { title: "Proteção Jurídica", desc: "Bloqueamos o roubo online retirando conteúdos vazados rapidamente e com força legal DMCA." }] },
    simulator: { tag: "CALCULADORA DE ROI", title1: "A psicologia da", title2: "audiência", desc: "O número de seguidores não dita sucesso. O envolvimento do seu nicho aumenta largamente os ganhos.", label: "A sua Audiência (Seguidores IG/TikTok)", subs: "seguidores", monthly: "Previsão de Ganhos Mensais", to: "até", disclaimer: "Não representa compromisso garantido.", disclaimer_text: "Estimativa que varia com cada indivíduo e consistência. A regularidade e conteúdos genuínos influenciam.", btn: "Estimar Ganhos VIP" },
    results: { tag: "RESULTADOS", title1: "Desempenhos", title2: "concretos", before: "Antes", start: "Início", after3m: "No Mês 3", months: ["Jan", "Fev", "Mar"], growth_title: "Escalada Exponencial", growth_desc: "Graças aos nossos funis, as redes recebem atenção convertida em MRR financeiro sustentável dia após dia.", stability_title: "Base Sustentada", stability_desc: "Temos o objetivo de fixar os pagamentos estabilizando os meses de modo seguro via técnicas avançadas." },
    models: { tag: "O Nosso Catálogo VIP", title1: "Modelos", title2: "Exclusivas Top" },
    reviews: { m1: "Sério? Não creio!! Bati +4k em 3 dias 😍", m2: "Isto é só o começo. As campanhas arrancaram agora nos US. 🚀", m3: "Meu Deus, começo a preparar as mídias hoje!! ✨", online: "Online", tag: "REDE PRIVADA", title1: "Casos de", title2: "Êxito Secretos", desc: "Preservamos o silêncio nos cenários de sucesso absoluto. A nossa comunicação interna revela os ganhos exponenciais na plataforma.", accompanied: "Mulheres promovidas ao 1% global de lucro" },
    faq: { tag: "TRANSPARÊNCIA", title1: "Dúvidas", title2: "frequentes", items: [{ q: "Posso permanecer anónima e bloquear familiares?", a: "Sim, absolutamente. Configuração geográfica exata esconde e bloqueia as contas conhecidas por segurança." }, { q: "Quem responde aos clientes em nome do perfil?", a: "Uma equipa profissional que imita estritamente o seu formato escrito amigável a gerar lucros massivos." }, { q: "Zero experiência de redes privadas, conseguirei ir bem?", a: "Naturalmente, prestamos o tutoriais necessários enquanto faz simples trabalhos fotográficos de base em casa." }, { q: "Estima-se o retorno gigante em quantos dias?", a: "Tipicamente observam-se faturamentos surpreendentemente maiores no finalizar do próprio mês introdutório." }] },
    onboarding: { tag: "PROCESSAMENTO ÚNICO", title1: "Integração", title2: "VIP", desc: "O manual de sucesso rigorosamente guiado, otimizando os passos perfeitos ao faturamento de excelência.", items: [{ title: "Auditoria Top & Tática", desc: "Mapeamento rigoroso definindo as audiências-alvo da base fiel pagante diária." }, { title: "Segurança Técnica", desc: "Fortificação geográfica na base do anonimato sem sobressaltos, removendo dados inóspitos DMCA." }, { title: "Visão Magnética de Visitantes Fartos", desc: "Direcionamos fluxos monetizados constantes ativamente às contas das assinantes VIP." }, { title: "Turno Da Conversão Escalada Otimizada", desc: "Sem as suas pausas de sono atrapalharem ativamos as trocas textuais e recolha de lucros." }] },
    form: { title: "Inscrição de Parceria", desc: "Selecionamos meticulosamente, retendo apenas dois membros mensais focados para garantir apoio puro.", name: "Nome Principal Completo", email: "Email Pessoal de Contato", socials: "Redes Sociais Públicas Existentes", has_platform: "Tem presença atuante e rentável prévia atualmente na internet?", has_platform_no: "Nada, venho do zero total querendo lucrar", has_platform_yes: "Sim, faturo e pretendo relaxar ou expandir", has_platform_past: "Testei mas caí devido a falha de suporte", which_platform: "Qual o titular ou plataforma online?", platform_link: "Anexe o link oficial (URL)", motivations: "Ambição, Objetivos e Foco", motivations_ph: "Defina limiares económicos ou o propósito deste compromisso na agência a fim de sucesso.", submit: "Transmitir Solicitação Integral Oficial Segura", submitting: "Arquivando Criptografada no Sistema Seguro...", secure_note: "Tranquilidade da base SSL forte sem vazamento perigoso fora de vias autorizadas absolutas.", success_title: "Procedimento Submissivo Certo", success_desc: "Comunicamos o seu apuramento, caso coincida ao crivo oficial da OnlyOne Management nos dias úteis subsequentes.", success_btn: "Refazer Em Caso De Nova Inscrição" }
  }
};
